# Generated by Django 4.1.5 on 2023-07-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
